# Generated by Django 4.2.1 on 2023-05-06 07:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(upload_to='LatestProject/feature_image')),
                ('project_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('project_start_date', models.CharField(max_length=100)),
                ('project_end_date', models.CharField(max_length=100)),
                ('about_the_project', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_images', models.ImageField(upload_to='LatestProject/Project-Image')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.latestproject')),
            ],
        ),
    ]
